services:
- type: pserv
  name: MBA-Legacy-MySQL
  plan: starter
  env: docker
  disk:
    name: mysql
    mountPath: /var/lib/mysql
    sizeGB: 10
  envVars:
  - fromGroup: MBA-Legacy-MySQL

# envVarGroups:
# - name: mysql
#   envVars:
#   - key: MYSQL_DATABASE
#     value: mysql
#   - key: MYSQL_USER
#     value: mba
#   - key: MYSQL_PASSWORD
#     value: SuperSecretPw22
#   - key: MYSQL_ROOT_PASSWORD
#     value: Mys3267!